### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by jansvanda** [ofa-/windguru#27]
Update the android app, add material style. I would help if you would want

**Comment by fambon** [comment]
Hey there @jansvanda !  I am not too sure what you mean by "android app" - may be what I call the "webapp" ? Anyway, you are more than welcome.  Would it be ok for you to go ahead and send-in a PR ?

**Comment by ofa-** [comment]
Hey there @jansvanda ! I am not too sure what you mean by "android app" - may be what I call the "webapp" ? Anyway, you are more than welcome. Would it be ok for you to go ahead and send-in a PR ?

**Comment by jansvanda** [comment]
I mean the windguru app in the play store ..

**Comment by ofa-** [comment]
Ah, then you are at the wrong repo.  There is no "android app" (android sdk) in here, only a "webapp" (just javascript) that runs in browsers.

Other folks are doing the official android windguru app ; not sure it is available in github though.
Maybe try this one: fedec93/WindGuru ?

**Comment by jansvanda** [comment]
Tried that, compiled with android studio, crashed on search. Can we talk czech?
